name = "telegram-bot-template"
compatibility_date = "2026-01-20"
main = "src/main.ts"

# Configure environment variables
[vars]
BOT_TOKEN = ""
BOT_WEBHOOK = ""
BOT_WEBHOOK_SECRET = ""
# 
[dev]
port = 3000