name = "telegram-bot-template"
compatibility_date = "2026-01-20"
main = "src/main.ts"

# Configure environment variables
[vars]
BOT_TOKEN = "8481175310:AAGVHEs3uBNUBwijrnzsGKx6WFVYjAXbUMA"
BOT_WEBHOOK = "https://el5vss-ip-223-84-224-139.tunnelmole.net"

[dev]
port = 3000